// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "77f5f05d-2068-4e6b-a5ed-b4e9f209db3f";

const char SSID[]               = "ABDULWAHAB 2469";    // Network SSID (name)
const char PASS[]               = "theoutside721";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "uwyU@tgcoUE2!v7V#AP6tL8!I";    // Secret device password

void onLampChange();

CloudLight lamp;
CloudTemperatureSensor temperature;
CloudIlluminance intensity;
CloudRelativeHumidity humidity;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(lamp, READWRITE, ON_CHANGE, onLampChange);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(intensity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
